# Generated by Django 2.1.3 on 2018-11-29 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_cousine', models.CharField(choices=[('am', 'American'), ('br', 'British'), ('ca', 'Caribbean'), ('ch', 'Chinese'), ('es', 'Spanish')], max_length=2)),
                ('allergens', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(0, 'Precio negativo no permitido')])),
            ],
        ),
    ]
